-- MySQL Script generated by MySQL Workbench
-- Sun Apr 21 00:44:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `Studentemail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStudent`),
  UNIQUE INDEX `Studentemail_UNIQUE` (`Studentemail` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Couselor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Couselor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Couselor` (
  `idCouselor` INT NOT NULL,
  `Couseloremail` VARCHAR(45) NULL,
  PRIMARY KEY (`idCouselor`),
  UNIQUE INDEX `Couseloremail_UNIQUE` (`Couseloremail` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Date` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Date` (
  `idDate` INT NOT NULL AUTO_INCREMENT,
  `DateValue` DATE NULL,
  `Couselor_idCouselor` INT NOT NULL,
  PRIMARY KEY (`idDate`),
  INDEX `fk_Date_Couselor1_idx` (`Couselor_idCouselor` ASC) VISIBLE,
  CONSTRAINT `fk_Date_Couselor1`
    FOREIGN KEY (`Couselor_idCouselor`)
    REFERENCES `mydb`.`Couselor` (`idCouselor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Slot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Slot` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Slot` (
  `idSlot` INT NOT NULL AUTO_INCREMENT,
  `SlotValue` VARCHAR(45) NULL,
  `Date_idDate` INT NOT NULL,
  PRIMARY KEY (`idSlot`),
  INDEX `fk_Slot_Date1_idx` (`Date_idDate` ASC) VISIBLE,
  CONSTRAINT `fk_Slot_Date1`
    FOREIGN KEY (`Date_idDate`)
    REFERENCES `mydb`.`Date` (`idDate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Student_Slot_Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student_Slot_Request` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Student_Slot_Request` (
  `Student_idStudent` INT NOT NULL,
  `Slot_idSlot` INT NOT NULL,
  PRIMARY KEY (`Student_idStudent`, `Slot_idSlot`),
  INDEX `fk_Student_has_Slot_Slot1_idx` (`Slot_idSlot` ASC) VISIBLE,
  INDEX `fk_Student_has_Slot_Student1_idx` (`Student_idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_Student_has_Slot_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Slot_Slot1`
    FOREIGN KEY (`Slot_idSlot`)
    REFERENCES `mydb`.`Slot` (`idSlot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`StudentBookingHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StudentBookingHistory` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`StudentBookingHistory` (
  `Student_idStudent` INT NOT NULL,
  `Slot_idSlot` INT NOT NULL,
  PRIMARY KEY (`Student_idStudent`, `Slot_idSlot`),
  INDEX `fk_Student_has_Slot_Slot2_idx` (`Slot_idSlot` ASC) VISIBLE,
  INDEX `fk_Student_has_Slot_Student2_idx` (`Student_idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_Student_has_Slot_Student2`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Slot_Slot2`
    FOREIGN KEY (`Slot_idSlot`)
    REFERENCES `mydb`.`Slot` (`idSlot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
